name: CI build

on:
  workflow_dispatch:

jobs:
  build-windows-msvc-x64:
    name: Build for Windows (MSVC x64)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        ref: zuma

    - uses: actions/checkout@v6
      with:
        repository: kyle-sylvestre/CircleShootApp
        path: src/CircleShootApp

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Install Ninja
      run: choco install ninja -y

    - name: Setup vcpkg (manifest mode)
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: vcpkg.json

    - name: Compile PvZ-Portable for Windows (MSVC)
      shell: pwsh
      run: |
        cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=Release -DCONSOLE=OFF -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static
        cmake --build build

        New-Item -ItemType Directory -Force -Path dist | Out-Null
        Copy-Item build/pvz-portable.exe dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: pvz-portable-windows-msvc-x64
        path: dist/


